# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
      - P1-time3/ReviewApp.ConsoleApp

variables:
    slnPath: P1-time3/ReviewApp.ConsoleApp

stages:
- stage: build
  
  jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
       debug:
        configuration: Debug
       release:
        configuration: Release   
    steps:
    - script: dotnet build --configuration $(configuration)
      displayName: dotnet build (script)    
      workingDirectory: $(slnPath)
    
  - job: build_windows_vs
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: dotnet build
      displayName: dotnet build (script)    
      workingDirectory: $(slnPath)
   

    